apiVersion: apps/v1
kind: Deployment
metadata:
  name: vingaard-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: vingaard-backend
  template:
    metadata:
      labels:
        app: vingaard-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
