apiVersion: apps/v1
kind: Deployment
metadata:
  name: vingaard-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: vingaard-frontend
  template:
    metadata:
      labels:
        app: vingaard-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}