services:
  frontend:
    image: ghcr.io/zekq88/vingaard-frontend:latest
    container_name: vingaard-frontend
    restart: always
    ports:
      - "8080:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: ghcr.io/zekq88/vingaard-backend:latest
    container_name: vingaard-backend
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        