services:
  frontend:
    build:
      context: .frontend/WebAppFrontend.Wasm
    container_name: vingaard-frontend
    restart: always
    ports:
      - "8080:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: vingaard-backend
    restart: always
    ports:
      - "8000:8000"