apiVersion: apps/v1
kind: Deployment
metadata:
  name: vingaard-backend
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: vingaard-backend
  template:
    metadata:
      labels:
        app: vingaard-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/zekq88/vingaard-backend:3dd84e5647653a9ee44e73887dd82fd02190c8ca
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: vingaard-backend-service
spec:
  selector:
    app: vingaard-backend
  ports:
    - port: 8000
      targetPort: 8000