frontend:
  image: ghcr.io/zekq88/vingaard-frontend:b077ebef77223e968d45687ab1d0628045be06d7
  replicas: 2
  port: 80

backend:
  image: ghcr.io/zekq88/vingaard-backend:b077ebef77223e968d45687ab1d0628045be06d7
  replicas: 2
  port: 8000

ingress:
  enable: true
  hosts:
    - vingaard-solutions.eu
    - www.vingaard-solutions.eu
  tlsSecretName: vingaard-tls
  clusterIssuer: letsencrypt-prod 