frontend:
  image: ghcr.io/zekq88/vingaard-frontend:afd3b168db6a5dca9c2da57ec78b2b8cbade25c6
  replicas: 2
  port: 80

backend:
  image: ghcr.io/zekq88/vingaard-backend:afd3b168db6a5dca9c2da57ec78b2b8cbade25c6
  replicas: 2
  port: 8000

ingress:
  enable: true
  hosts:
    - vingaard-solutions.eu
    - www.vingaard-solutions.eu
  tlsSecretName: vingaard-tls
  clusterIssuer: letsencrypt-prod 